<?php

namespace JetCharters\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AircraftTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AircraftTypeRepository extends EntityRepository
{
    public function findByType($airport_type, $city, $radius) {

        $sql = $this->getEntityManager()->createQueryBuilder()
            ->select( 'a', 'm', 'i' )
            ->from('JetChartersAppBundle:AircraftType', 'a')
            ->leftjoin('a.aircraftModel', 'm')
            ->leftjoin('m.charterAircraft', 'l')
            ->leftjoin('m.images', 'i')
            ->leftjoin('l.location', 'k');

            if ($airport_type !='' ){
                $sql = $sql->where('a.id = :airport_type_id')->setParameter('airport_type_id', $airport_type);
            }
            if(!empty($city)){
                $sql = $sql->andWhere('k.closestCity IN (:closest_city)')->setParameter('closest_city', $city);
            }
            if($radius !=''){
                $sql = $sql->andWhere('k.closestCityDistanceMiles <= :radius')->setParameter('radius', $radius);
            }

        return  $sql->getQuery()->execute();

    }
}
