<?php

namespace JetCharters\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogPostCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostCategoryRepository extends EntityRepository
{
   

}
