<?php

namespace JetCharters\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BulkMailerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BulkMailerRepository extends EntityRepository
{
}
